# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DoImportanceSamplerCpp <- function(NumberOfPoints, Model, Algorithm, MaxVectorSize) {
    .Call('_IntractableLikelihood_DoImportanceSamplerCpp', PACKAGE = 'IntractableLikelihood', NumberOfPoints, Model, Algorithm, MaxVectorSize)
}

